version: '3.7'

services:
  iris:
    build:
            context: ./faq
            dockerfile: Dockerfile
    image: faq:iris
    init: true
    restart: always
    hostname: irisforfaq
    container_name: faq-iris
    environment:
      - ISC_DATA_DIRECTORY=/opt/config/iris
      - TZ=JST-9
    volumes:
      - ./config:/opt/config
      - /usr/FAQsetup:/usr/FAQsetup
    ports:
            - 52773:52773
            - 1972:1972
  web:
    build:
            context: ./web
            dockerfile: Dockerfile
    init: true
    image: faq:web
    restart: always
    hostname: apacheforfaq
    container_name: faq-web
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: JST-9
      SERVER_HOST: iris
      SERVER_PORT: 1972
volumes:
  config:
